import React, { useState } from "react";
import { Check, KeyRound, ShieldCheck } from "lucide-react";
import { BrandLogo } from "@/components/BrandLogo";
import { supabase } from "@/lib/supabase";

export const ResetPassword = ({ session, onFinished }) => {
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false);
  const submit = async event => { event.preventDefault(); setMessage(""); if (password.length < 12) { setMessage("Use at least 12 characters."); return; } if (password !== confirm) { setMessage("Passwords do not match."); return; } setBusy(true); const { error } = await supabase.auth.updateUser({ password }); if (error) { setMessage(error.message); setBusy(false); return; } localStorage.removeItem("mahaflow-password-recovery"); setDone(true); setBusy(false); };
  const finish = async () => { await supabase.auth.signOut({ scope: "local" }); window.history.replaceState({}, document.title, "/"); onFinished(); };
  return <main className="reset-shell" data-testid="reset-password-page"><header><BrandLogo testId="reset-password-logo"/><span><ShieldCheck size={15}/>Secure recovery</span></header><section className="reset-panel"><div className="modal-icon">{done ? <Check/> : <KeyRound/>}</div>{done ? <><span className="eyebrow purple">PASSWORD UPDATED</span><h1>Your password is ready.</h1><p>Sign in again using your email and new MahaFlow password.</p><button className="primary-button" data-testid="reset-password-finish-button" onClick={finish}>Return to sign in</button></> : !session ? <><span className="eyebrow purple">RECOVERY LINK</span><h1>This link is unavailable.</h1><p>Request a new password email from the MahaFlow sign-in screen.</p><button className="outline-button" data-testid="reset-password-back-button" onClick={() => { window.history.replaceState({}, document.title, "/"); onFinished(); }}>Back to sign in</button></> : <form onSubmit={submit}><span className="eyebrow purple">CHOOSE A PASSWORD</span><h1>Set your MahaFlow password.</h1><p>Signed in securely as {session.user.email}. This creates a Supabase password without changing your Google account.</p><label>New password<input type="password" minLength="12" value={password} onChange={event => setPassword(event.target.value)} data-testid="new-password-input" required/></label><label>Confirm password<input type="password" minLength="12" value={confirm} onChange={event => setConfirm(event.target.value)} data-testid="confirm-password-input" required/></label><button className="primary-button" data-testid="update-password-button" disabled={busy}>{busy ? "Updating…" : "Update password"}</button></form>}{message && <div className="inline-message" data-testid="reset-password-message">{message}</div>}</section></main>;
};