import React, { useEffect, useState } from "react";
import { Activity, ArrowRight, BusFront, Camera, KeyRound, MapPin, ShieldCheck, Users } from "lucide-react";
import { listAccessCodes, listAuthorities, listCameras, listCrowdReadings, listFacilities, listTransportServices } from "@/lib/supabaseData";
import { LoadingState, SectionHeader } from "@/components/workspace/WorkspaceUI";
import { useLanguage } from "@/i18n";

export const OverviewPage = ({ role, session, onNavigate }) => {
  const { t } = useLanguage();
  const [metrics, setMetrics] = useState(null); const [error, setError] = useState("");
  const content = {
    passenger: { eyebrow: t("overview.eyebrow"), title: t("overview.title"), description: t("overview.description"), next: "Bus & rail" },
    authority: { eyebrow: t("overview.eyebrow"), title: t("overview.title"), description: t("overview.description"), next: "Live crowd" },
    developer: { eyebrow: t("overview.eyebrow"), title: t("overview.title"), description: t("overview.description"), next: "Access codes" },
  }[role];
  useEffect(() => { let active = true; const load = async () => { try { let next; if (role === "passenger") { const [services, facilities, readings] = await Promise.all([listTransportServices(), listFacilities(), listCrowdReadings()]); next = [[services.length,t("overview.activeServices"),BusFront],[facilities.length,t("overview.mappedFacilities"),MapPin],[readings.length,t("overview.liveReadings"),Users]]; } else if (role === "authority") { const [services, cameras, readings] = await Promise.all([listTransportServices({ ownerId: session.user.id }), listCameras(session.user.id), listCrowdReadings({ ownerId: session.user.id })]); next = [[services.length,t("overview.activeServices"),BusFront],[cameras.length,t("overview.mappedFacilities"),Camera],[readings.length,t("overview.liveReadings"),Activity]]; } else { const [facilities, codes, authorities] = await Promise.all([listFacilities(), listAccessCodes(), listAuthorities()]); next = [[facilities.length,t("overview.mappedFacilities"),MapPin],[codes.filter(item => item.status === "active").length,t("overview.activeServices"),KeyRound],[authorities.length,t("overview.liveReadings"),ShieldCheck]]; } if (active) setMetrics(next); } catch (requestError) { if (active) setError(requestError.message); } }; void load(); return () => { active = false; }; }, [role, session.user.id, t]);
  return <><SectionHeader eyebrow={content.eyebrow} title={content.title} description={content.description}/><section className="hero-band" data-testid="overview-hero"><div><span className="eyebrow">{t("overview.liveWorkspace")}</span><h2>{error ? t("common.error") : t("overview.heroTitle")}</h2><p>{error || t("overview.heroDescription")}</p><button className="dark-button" data-testid="overview-primary-action" onClick={() => onNavigate(content.next)}>{t("overview.open")} {content.next}<ArrowRight size={17}/></button></div><div className="hero-orbit"><div className="orbit-ring"><span><BusFront size={24}/></span><span><Camera size={22}/></span><span><Users size={21}/></span></div><div className="orbit-core"><b>{metrics ? metrics.reduce((sum,item) => sum + Number(item[0]), 0) : "—"}</b><small>{t("overview.liveRecords")}</small></div></div></section>{!metrics ? <LoadingState label={t("overview.loading")}/> : <div className="metric-grid overview-metrics">{metrics.map(([value,label,Icon]) => <article className="metric" key={label} data-testid={`overview-metric-${label.toLowerCase().replaceAll(" ", "-")}`}><div className="metric-icon"><Icon size={18}/></div><b>{value}</b><span>{label}</span><small>Supabase · RLS protected</small></article>)}</div>}</>;
};