import React, { useEffect, useState } from "react";
import { Activity, ArrowRight, BusFront, Camera, KeyRound, MapPin, ShieldCheck, Users } from "lucide-react";
import { listAccessCodes, listAuthorities, listCameras, listCrowdReadings, listFacilities, listTransportServices } from "@/lib/supabaseData";
import { LoadingState, SectionHeader } from "@/components/workspace/WorkspaceUI";

const config = {
  passenger: { eyebrow: "MAHARASHTRA MOBILITY", title: "Move through Maharashtra.", description: "Search verified services and see real crowd information before you travel.", next: "Bus & rail" },
  authority: { eyebrow: "FACILITY OPERATIONS", title: "Operations at a glance.", description: "Monitor your registered services, cameras, and detector records.", next: "Live crowd" },
  developer: { eyebrow: "PLATFORM CONTROL", title: "Keep the network trusted.", description: "Manage facilities, authority access, and platform integrations.", next: "Access codes" },
};

export const OverviewPage = ({ role, session, onNavigate }) => {
  const [metrics, setMetrics] = useState(null); const [error, setError] = useState(""); const content = config[role];
  useEffect(() => { let active = true; const load = async () => { try { let next; if (role === "passenger") { const [services, facilities, readings] = await Promise.all([listTransportServices(), listFacilities(), listCrowdReadings()]); next = [[services.length,"Active services",BusFront],[facilities.length,"Mapped facilities",MapPin],[readings.length,"Live readings",Users]]; } else if (role === "authority") { const [services, cameras, readings] = await Promise.all([listTransportServices({ ownerId: session.user.id }), listCameras(session.user.id), listCrowdReadings({ ownerId: session.user.id })]); next = [[services.length,"Registered services",BusFront],[cameras.length,"CCTV endpoints",Camera],[readings.length,"Detector readings",Activity]]; } else { const [facilities, codes, authorities] = await Promise.all([listFacilities(), listAccessCodes(), listAuthorities()]); next = [[facilities.length,"Facilities",MapPin],[codes.filter(item => item.status === "active").length,"Active codes",KeyRound],[authorities.length,"Authorities",ShieldCheck]]; } if (active) setMetrics(next); } catch (requestError) { if (active) setError(requestError.message); } }; void load(); return () => { active = false; }; }, [role, session.user.id]);
  return <><SectionHeader eyebrow={content.eyebrow} title={content.title} description={content.description}/><section className="hero-band" data-testid="overview-hero"><div><span className="eyebrow">LIVE SUPABASE WORKSPACE</span><h2>{error ? "Live data needs attention." : "Your network, without placeholders."}</h2><p>{error || "Every count below comes from protected database records. Crowd values remain empty until a real authority or YOLO26n worker publishes them."}</p><button className="dark-button" data-testid="overview-primary-action" onClick={() => onNavigate(content.next)}>Open {content.next}<ArrowRight size={17}/></button></div><div className="hero-orbit"><div className="orbit-ring"><span><BusFront size={24}/></span><span><Camera size={22}/></span><span><Users size={21}/></span></div><div className="orbit-core"><b>{metrics ? metrics.reduce((sum,item) => sum + Number(item[0]), 0) : "—"}</b><small>live records</small></div></div></section>{!metrics ? <LoadingState label="Calculating verified totals…"/> : <div className="metric-grid overview-metrics">{metrics.map(([value,label,Icon]) => <article className="metric" key={label} data-testid={`overview-metric-${label.toLowerCase().replaceAll(" ", "-")}`}><div className="metric-icon"><Icon size={18}/></div><b>{value}</b><span>{label}</span><small>Supabase · RLS protected</small></article>)}</div>}</>;
};