import React, { useMemo, useState } from "react";
import { Ban, Building2, Check, KeyRound, MapPinned, Palette, Plus, ShieldCheck, UserCheck } from "lucide-react";
import MapView from "@/components/MapView";
import { addFacility, blockAccessCode, createAccessCode, getBranding, listAccessCodes, listAuthorities, listFacilities, saveBranding, setAuthorityStatus } from "@/lib/supabaseData";
import { useWorkspaceData } from "@/hooks/useWorkspaceData";
import { EmptyState, ErrorState, LoadingState, SectionHeader, StatusBadge } from "@/components/workspace/WorkspaceUI";
import { SettingsPanel } from "@/components/workspace/SettingsPanel";

const AccessCodeManager = () => {
  const codes = useWorkspaceData(() => listAccessCodes(), []);
  const facilities = useWorkspaceData(() => listFacilities(), []);
  const [facilityId, setFacilityId] = useState(""); const [days, setDays] = useState(30); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const selectedId = facilityId || facilities.data[0]?.id || "";
  const create = async () => { if (!selectedId) { setMessage("No active facility is available. Add a facility first."); return; } setBusy(true); setMessage(""); try { const created = await createAccessCode(selectedId, days); setMessage(`Created ${created.code} for ${created.location_name}.`); await codes.reload(); } catch (error) { setMessage(`Code generation failed: ${error.message}`); } finally { setBusy(false); } };
  const block = async id => { await blockAccessCode(id); await codes.reload(); };
  return <><SectionHeader eyebrow="DEVELOPER · CONTROL" title="Access codes" description="Generate one-time MFB/MFR codes bound to a real facility." action={<button className="dark-button" data-testid="generate-access-code-button" disabled={busy || facilities.loading || !selectedId} onClick={create}><Plus size={17}/>{busy ? "Generating…" : "Generate code"}</button>}/><div className="filter-bar"><label>Facility<select value={selectedId} onChange={event => setFacilityId(event.target.value)} data-testid="access-code-facility-select">{facilities.data.map(item => <option key={item.id} value={item.id} label={`${item.kind === "bus" ? "MFB" : "MFR"} · ${item.name}`}/>)}</select></label><label>Expires in<input type="number" min="1" max="90" value={days} onChange={event => setDays(Number(event.target.value))} data-testid="access-code-expiry-input"/><span>days</span></label></div>{message && <div className="notice-line" data-testid="access-code-message">{message}</div>}{codes.loading ? <LoadingState/> : codes.error ? <ErrorState message={codes.error}/> : codes.data.length ? <div className="code-table">{codes.data.map(code => <article key={code.id} data-testid={`access-code-${code.id}`}><div className={`service-mode ${code.network}`}>{code.network === "bus" ? "MFB" : "MFR"}</div><span className="code-value"><b>{code.code}</b><small>{code.location_name} · {code.district}</small></span><StatusBadge value={code.status}/><span><small>Expires</small><b>{new Date(code.expires_at).toLocaleDateString()}</b></span>{code.status === "active" ? <button className="outline-button danger" data-testid={`block-code-${code.id}`} onClick={() => block(code.id)}><Ban size={15}/>Block</button> : <span className="joined-name">{code.joined_name || "Not assigned"}</span>}</article>)}</div> : <EmptyState icon={KeyRound} title="No access codes" message="Choose a facility and generate the first secure authority code." testId="access-codes-empty"/>}</>;
};

const AuthorityManager = () => {
  const authorities = useWorkspaceData(() => listAuthorities(), []);
  const update = async (id, status) => { await setAuthorityStatus(id, status); await authorities.reload(); };
  return <><SectionHeader eyebrow="DEVELOPER · TRUST" title="Authorities" description="Review and control every registered facility operator."/>{authorities.loading ? <LoadingState/> : authorities.error ? <ErrorState message={authorities.error}/> : authorities.data.length ? <div className="authority-list">{authorities.data.map(person => <article key={person.id} data-testid={`authority-${person.id}`}><div className="authority-avatar">{person.display_name?.slice(0,2).toUpperCase()}</div><span><b>{person.display_name}</b><small>{person.email} · {person.mobile || "No mobile"}</small></span><span><b>{person.facility_name || "Facility pending"}</b><small>{person.network || "—"} · {person.designation || "Operator"}</small></span><StatusBadge value={person.status}/><select value={person.status} onChange={event => update(person.id, event.target.value)} data-testid={`authority-status-${person.id}`}><option value="active">Active</option><option value="suspended">Suspended</option><option value="banned">Banned</option></select></article>)}</div> : <EmptyState icon={ShieldCheck} title="No authority accounts" message="Completed one-time-code registrations will appear here." testId="authorities-empty"/>}</>;
};

const FacilityManager = () => {
  const facilities = useWorkspaceData(() => listFacilities(), []); const [message, setMessage] = useState("");
  const markers = useMemo(() => facilities.data.map(item => ({ lat: item.latitude, lng: item.longitude, label: item.name, level: item.status })), [facilities.data]);
  const add = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await addFacility({ name: form.get("name"), kind: form.get("kind"), state: form.get("state"), district: form.get("district"), address: form.get("address"), latitude: Number(form.get("latitude")), longitude: Number(form.get("longitude")), status: "active" }); event.currentTarget.reset(); await facilities.reload(); setMessage("Facility added."); } catch (error) { setMessage(error.message); } };
  return <><SectionHeader eyebrow="DEVELOPER · NETWORK" title="Facilities" description="Manage the physical bus and railway locations that anchor MahaFlow."/><div className="facility-layout"><form className="data-form" onSubmit={add}><h3>Add facility</h3><div className="form-grid"><label>Name<input name="name" required data-testid="facility-name-input"/></label><label>Type<select name="kind" data-testid="facility-kind-select"><option value="bus">Bus Stand</option><option value="railway">Railway Station</option></select></label><label>State<input name="state" defaultValue="Maharashtra" required data-testid="facility-state-input"/></label><label>District<input name="district" required data-testid="facility-district-input"/></label><label>Latitude<input name="latitude" type="number" step="any" required data-testid="facility-latitude-input"/></label><label>Longitude<input name="longitude" type="number" step="any" required data-testid="facility-longitude-input"/></label></div><label>Address<input name="address" required data-testid="facility-address-input"/></label><button className="primary-button" data-testid="add-facility-button"><Plus size={17}/>Add facility</button>{message && <div className="notice-line" data-testid="facility-message">{message}</div>}</form><MapView markers={markers}/></div><div className="facility-grid">{facilities.data.map(item => <article key={item.id} data-testid={`facility-${item.id}`}><div className={`service-mode ${item.kind}`}>{item.kind === "bus" ? "MFB" : "MFR"}</div><span><b>{item.name}</b><small>{item.address}</small></span><span><MapPinned size={14}/>{item.latitude.toFixed(4)}, {item.longitude.toFixed(4)}</span><StatusBadge value={item.status}/></article>)}</div></>;
};

const Branding = ({ session }) => {
  const branding = useWorkspaceData(() => getBranding(), []);
  const [form, setForm] = useState(null); const [message, setMessage] = useState("");
  const values = form || branding.data || { app_name: "MahaFlow", tagline: "Smarter Travel. A Better Maharashtra.", primary_color: "#0561DF", accent_color: "#8B35E9", logo_url: "/mahaflow-logo.webp" };
  const set = (key, value) => setForm({ ...values, [key]: value });
  const save = async () => { try { const saved = await saveBranding(session.user.id, values); setForm(saved); setMessage("Branding saved."); } catch (error) { setMessage(error.message); } };
  return <><SectionHeader eyebrow="DEVELOPER · BRAND SYSTEM" title="Branding" description="Manage the shared identity shown across all MahaFlow workspaces."/><div className="branding-layout"><section className="settings-section"><div className="settings-title"><Palette/><div><h3>Application identity</h3><p>Changes are stored centrally in Supabase.</p></div></div><label>Application name<input value={values.app_name} onChange={event => set("app_name", event.target.value)} data-testid="branding-name-input"/></label><label>Tagline<input value={values.tagline} onChange={event => set("tagline", event.target.value)} data-testid="branding-tagline-input"/></label><div className="form-grid"><label>Primary color<input type="color" value={values.primary_color} onChange={event => set("primary_color", event.target.value)} data-testid="branding-primary-color-input"/></label><label>Accent color<input type="color" value={values.accent_color} onChange={event => set("accent_color", event.target.value)} data-testid="branding-accent-color-input"/></label></div><label>Logo URL<input value={values.logo_url || ""} onChange={event => set("logo_url", event.target.value)} data-testid="branding-logo-url-input"/></label><button className="primary-button" data-testid="branding-save-button" onClick={save}><Check size={17}/>Save branding</button>{message && <div className="notice-line" data-testid="branding-message">{message}</div>}</section><section className="brand-preview" style={{ "--preview-primary": values.primary_color, "--preview-accent": values.accent_color }} data-testid="branding-preview"><img src={values.logo_url || "/mahaflow-logo.webp"} alt="Current MahaFlow branding"/><span>LIVE PREVIEW</span><h2>{values.app_name}</h2><p>{values.tagline}</p><span className="preview-button" data-testid="branding-preview-action">Primary action</span></section></div></>;
};

export const DeveloperWorkspace = ({ page, session, profile, theme, setTheme }) => {
  if (page === "Access codes") return <AccessCodeManager/>;
  if (page === "Authorities") return <AuthorityManager/>;
  if (page === "Facilities") return <FacilityManager/>;
  if (page === "Branding") return <Branding session={session}/>;
  if (page === "Settings") return <SettingsPanel {...{ role: "developer", session, profile, theme, setTheme }}/>;
  return null;
};