import React, { useMemo, useState } from "react";
import { Bookmark, BusFront, Clock3, MapPin, Navigation, Search, TrainFront, Trash2, Users } from "lucide-react";
import MapView from "@/components/MapView";
import { deleteSavedRoute, listCrowdPredictions, listCrowdReadings, listFacilities, listSavedRoutes, listTransportServices, saveRoute } from "@/lib/supabaseData";
import { useWorkspaceData } from "@/hooks/useWorkspaceData";
import { EmptyState, ErrorState, LoadingState, SectionHeader, StatusBadge } from "@/components/workspace/WorkspaceUI";
import { SettingsPanel } from "@/components/workspace/SettingsPanel";

const TransportExplorer = ({ session }) => {
  const services = useWorkspaceData(() => listTransportServices(), []);
  const [query, setQuery] = useState(""); const [mode, setMode] = useState("all"); const [message, setMessage] = useState("");
  const filtered = useMemo(() => services.data.filter(item => (mode === "all" || item.mode === mode) && [item.origin,item.destination,item.service_number,item.service_name].join(" ").toLowerCase().includes(query.toLowerCase())), [services.data, query, mode]);
  const save = async service => { try { await saveRoute(session.user.id, service); setMessage(`${service.service_number} saved.`); } catch (error) { setMessage(error.message); } };
  return <><SectionHeader eyebrow="PASSENGER · LIVE NETWORK" title="Bus & rail" description="Search services registered by verified transport authorities."/><div className="filter-bar"><label><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} data-testid="transport-search-input" placeholder="Origin, destination, or service number"/></label><div className="segmented"><button className={mode === "all" ? "active" : ""} data-testid="transport-filter-all" onClick={() => setMode("all")}>All</button><button className={mode === "bus" ? "active" : ""} data-testid="transport-filter-bus" onClick={() => setMode("bus")}>Bus</button><button className={mode === "railway" ? "active" : ""} data-testid="transport-filter-railway" onClick={() => setMode("railway")}>Rail</button></div></div>{message && <div className="notice-line" data-testid="transport-save-message">{message}</div>}{services.loading ? <LoadingState/> : services.error ? <ErrorState message={services.error}/> : filtered.length ? <div className="service-list">{filtered.map(service => <article className="service-row" key={service.id} data-testid={`transport-service-${service.id}`}><div className={`service-mode ${service.mode}`}>{service.mode === "bus" ? <BusFront/> : <TrainFront/>}</div><div className="service-main"><span>{service.service_number}</span><b>{service.origin} <Navigation size={14}/> {service.destination}</b><small>{service.service_name}</small></div><div className="service-time"><Clock3 size={14}/><b>{String(service.departure_time).slice(0,5)}</b><small>{service.bay_or_platform || "Platform pending"}</small></div><StatusBadge value={service.status}/><button className="icon-button" title="Save route" aria-label={`Save ${service.service_number}`} data-testid={`save-route-${service.id}`} onClick={() => save(service)}><Bookmark size={17}/></button></article>)}</div> : <EmptyState icon={BusFront} title="No matching services" message="Verified authority schedules will appear here as soon as they are registered." testId="transport-empty"/>}</>;
};

const CrowdMap = () => {
  const facilities = useWorkspaceData(() => listFacilities(), []); const readings = useWorkspaceData(() => listCrowdReadings(), []); const predictions = useWorkspaceData(() => listCrowdPredictions(), []);
  const latest = useMemo(() => { const seen = new Set(); return readings.data.filter(item => { const key = `${item.facility_id}-${item.zone}`; if (seen.has(key)) return false; seen.add(key); return true; }); }, [readings.data]);
  const markers = facilities.data.map(facility => { const reading = latest.find(item => item.facility_id === facility.id); return { lat: facility.latitude, lng: facility.longitude, label: facility.name, level: reading?.crowd_level || "Awaiting live data" }; });
  return <><SectionHeader eyebrow="PASSENGER · CROWD INTELLIGENCE" title="Crowd map" description="Live detector readings and time-stamped predictions remain clearly separated."/><div className="map-layout"><MapView markers={markers}/><aside className="map-feed"><h3>Latest verified readings</h3>{readings.loading ? <LoadingState/> : latest.length ? latest.map(item => <div className="feed-row" key={item.id} data-testid={`public-crowd-${item.id}`}><span><b>{item.mahaflow_facilities?.name || "Transit facility"}</b><small>{item.zone} · {item.people_count} people · {item.source}</small></span><StatusBadge value={item.crowd_level}/></div>) : <EmptyState icon={Users} title="No live readings yet" message="Real YOLO26n or authority readings will appear here; MahaFlow does not fabricate counts." testId="crowd-readings-empty"/>}</aside></div><section className="prediction-section"><div className="section-title"><div><h3>Upcoming crowd predictions</h3><p>Only model-generated records with a future timestamp are shown.</p></div></div>{predictions.data.length ? <div className="prediction-list">{predictions.data.map(item => <article key={item.id} data-testid={`crowd-prediction-${item.id}`}><span><b>{item.mahaflow_facilities?.name || "Transit facility"}</b><small>{item.zone} · {new Date(item.prediction_for).toLocaleString()}</small></span><strong>{item.predicted_count}</strong><StatusBadge value={item.crowd_level}/></article>)}</div> : <EmptyState icon={Users} title="Predictions are not connected yet" message="Your YOLO26n pipeline can write predictions to the secured prediction table." testId="crowd-predictions-empty"/>}</section></>;
};

const SavedRoutes = ({ session }) => {
  const routes = useWorkspaceData(() => listSavedRoutes(session.user.id), [session.user.id]);
  const remove = async routeId => { await deleteSavedRoute(session.user.id, routeId); await routes.reload(); };
  return <><SectionHeader eyebrow="PASSENGER · PERSONAL" title="Saved routes" description="Your routes are private and protected by row-level security."/>{routes.loading ? <LoadingState/> : routes.error ? <ErrorState message={routes.error}/> : routes.data.length ? <div className="saved-grid">{routes.data.map(route => <article className="saved-card" key={route.route_id} data-testid={`saved-route-${route.route_id}`}><div className="service-mode">{route.mode === "railway" ? <TrainFront/> : <BusFront/>}</div><span><small>{route.service_number || route.mode}</small><b>{route.origin || "Origin"} → {route.destination || route.route_id}</b></span><button className="icon-button" aria-label="Remove saved route" data-testid={`delete-saved-route-${route.route_id}`} onClick={() => remove(route.route_id)}><Trash2 size={16}/></button></article>)}</div> : <EmptyState icon={Bookmark} title="No saved routes" message="Save a service from Bus & rail for quick access here." testId="saved-routes-empty"/>}</>;
};

export const PassengerWorkspace = ({ page, session, profile, theme, setTheme }) => {
  if (page === "Bus & rail") return <TransportExplorer session={session}/>;
  if (page === "Crowd map") return <CrowdMap/>;
  if (page === "Saved routes") return <SavedRoutes session={session}/>;
  if (page === "Settings") return <SettingsPanel {...{ role: "passenger", session, profile, theme, setTheme }}/>;
  return null;
};